name: Build & Deploy Jekyll Site

on:
  push:
    branches:
      - main                # מפעיל רק על ענף main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build site in Docker
        run: |
          docker pull jekyll/builder:latest
          docker run --rm \
            -v "${{ github.workspace }}:/srv/jekyll:delegated" \
            -v "${{ github.workspace }}/_site:/srv/jekyll/_site" \
            jekyll/builder:latest \
            jekyll build --future

      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v3
        with:
          name: site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
